Replace carrier_notes to carrier_note
NaN-tic/trytond-carrier_send_shipments_nacex pull request #4
Opened 2024-07-09 08:06 UTC by nan-tic-dev

#168436

2024-07-18 09:08 UTC, bernatnan approved these changes
LGTM

2024-07-22 18:47 UTC, bernatnan requested changes

2024-07-22 18:47 UTC, bernatnan commented on shipment.py
> +                blocks = split_into_blocks(unaccent(shipment.carrier_note).rstrip(), max_length=38)
PEP8 ¿? width = 79 or 80.

2024-07-23 05:09 UTC, raimonesteve commented on shipment.py
> +                blocks = split_into_blocks(unaccent(shipment.carrier_note).rstrip(), max_length=38)
See 4c3d32ab9da93b7c5c08b648f5a9881f89f5fc35

2024-07-23 14:28 UTC, bernatnan requested changes
> Only one tab for each parenthesis.

See 1519d78be6b0bb16004f3f9bdc870b5a205988e1

2024-07-25 13:14 UTC, merged